name: GitHub Actions Environment Vars, etc
on: push

jobs:
  job-number-two:
    name: Output some GitHubActions Variables
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: |
          echo 'Home: ${HOME}'
          echo 'Workspace: ${GITHUB_WORKSPACE}'
          echo 'Actor: ${GITHUB_ACTOR}'
          echo 'Token: ${GITHUB_TOKEN}'

      - run: |
          echo "Profile1: ${MAVEN_PROFILE}"

      - name: Set a Release Profile EnvVar for Maven
        run: echo "MAVEN_PROFILE=-P release" >> $GITHUB_ENV
        if:  startsWith(github.ref, 'refs/tags/v')

      - name: Set a NotRelease Profile EnvVar for Maven
        run: echo "MAVEN_PROFILE=-P NotRelease" >> $GITHUB_ENV
        if:  ${{ ! startsWith(github.ref, 'refs/tags/v') }}

      - run: |
          echo "Profile2: ${MAVEN_PROFILE}"

      - name: Copy Maven settings if they exist
        run: (cp "${GITHUB_WORKSPACE}/.github/resources/maven_settings.xml" "${HOME}/.m2/settings.xml") || true

      - name: Copy Maven settings if they don't exist
        run: (cp "${GITHUB_WORKSPACE}/.github/resources/maven_settings2.xml" "${HOME}/.m2/settings.xml") || true
