name: GitHub Actions Environment Vars, etc
on:
  push:
  release:
    types: [published]


jobs:
  job-number-two:
    name: Output some GitHubActions Variables
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Output Job info!
        env:
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          echo "Home: ${HOME}"
          echo "Workspace: ${GITHUB_WORKSPACE}"
          echo "Actor: ${GITHUB_ACTOR}"
          echo "Token: ${GITHUB_TOKEN}
          echo "Event Name: ${GITHUB_EVENTNAME}"
          echo "Even2 Name: ${{ github.event_name }}"
          echo "GITHUB_DEFAULT_BRANCH: ${GITHUB_DEFAULT_BRANCH}"
          echo 'GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}''
          echo 'Repo Object: ${{ github.event.repository }}'
          echo 'Event Object: ${{ github.event }}'
          echo 'Event Name: ${{ github.event_name }}'

      - name: Set a Release Profile EnvVar for Maven (Push Only)
        run: echo "MAVEN_PROFILE=-P push" >> $GITHUB_ENV
        if:  github.event_name == 'push'

      - name: Set a Release Profile EnvVar for Maven (Tag not Release)
        run: echo "MAVEN_PROFILE=-P version" >> $GITHUB_ENV
        if:  startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'

      - name: Set a Release Profile EnvVar for Maven (Release not Tag)
        run: echo "MAVEN_PROFILE=-P release" >> $GITHUB_ENV
        if:  startsWith(github.ref, 'refs/tags/v') && startsWith(github.event_name, 'release')

      - name: Set a NotRelease Profile EnvVar for Maven
        run: echo "MAVEN_PROFILE=-P NotRelease" >> $GITHUB_ENV
        if:  ${{ ! startsWith(github.ref, 'refs/tags/v') }}

      - run: |
          echo "Resulting Profile: ${MAVEN_PROFILE}"

      - name: Is this a push to default branch? 1
        if:  format('refs/heads/{0}', ${{ github.event.repository.default_branch }}) == github.ref }}
        run: |
          echo "This is a push to the default branch: ${{ github.ref }}"

      - name: Is this a push to default branch? 2
        if:  github.ref == format('refs/heads/{0}', env.default_branch)
        run: |
          echo "This is a push to the default branch: ${{ github.ref }}"

      - name: Is this a push to default branch? 3
        env:
          IS_DEFAULT: github.ref == format('refs/heads/{0}', env.default_branch)
          IS_DEFAULT2: ${{ github.ref == format('refs/heads/{0}', env.default_branch) }}
        run: |
          echo "Results:"
          echo "IS_DEFAULT: ${IS_DEFAULT}"
          echo "IS_DEFAULT2: ${IS_DEFAULT2}"

      - name: Is this just a normal non-release push? 1
        if:  contains( ${{ env.MAVEN_PROFILE }}, 'push')
        run: |
          echo "Resulting Profile: ${MAVEN_PROFILE}"

      - name: Is this just a normal non-release push? 2
        if:  contains(env.MAVEN_PROFILE, 'push')
        run: |
          echo "Resulting Profile: ${MAVEN_PROFILE}"

      - name: Is this just a normal non-release push? 3
        if:  ${{ env.MAVEN_PROFILE ~= 'push' }}
        run: |
          echo "Resulting Profile: ${MAVEN_PROFILE}"

