name: GitHub Actions Environment Vars, etc
on: push

jobs:
  job-number-two:
    name: Output some GitHubActions Variables
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: echo "${HOME}"
      - run: echo "${GITHUB_WORKSPACE}"
      - run: echo "${GITHUB_ACTOR}"
      - run: echo "${GITHUB_TOKEN}"
      - run: cat "${GITHUB_WORKSPACE}/.github/resources/maven_settings.xml"
      - run: file "${GITHUB_WORKSPACE}/.github/resources/maven_settings.xml" || true
      - run: file "${HOME}/.m2/settings.xml" || true
      - run: diff "${GITHUB_WORKSPACE}/.github/resources/maven_settings.xml" "${HOME}/.m2/settings.xml" || true
      - run: cat "${HOME}/.m2/settings.xml" 2>/dev/null || true
      - run: (test -f "${HOME}/.m2/settings.xml" && cat "${HOME}/.m2/settings.xml") || true
      - run: (test -f "${HOME}/.m2/settings2.xml" && cat "${HOME}/.m2/settings2.xml") || echo "File does not exist, safely skipping"

      - run: (test -f "${settings_file}" && cat "${settings_file}") || echo "File does not exist, blerch"
        env:
          settings_file: "${HOME}/.m2/settings.xml"
