name: Specific Maven version example
on: push

jobs:
  job-number-two:
    name: Output some GitHubActions Variables
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: echo "${HOME}"
      - run: echo "${GITHUB_WORKSPACE}"
      - run: echo "${GITHUB_ACTOR}"
      - run: echo "${GITHUB_TOKEN}"
      - run: cat "${GITHUB_WORKSPACE}/.github/actions_resources/maven_settings.xml"
      - run: diff "${GITHUB_WORKSPACE}/.github/actions_resources/maven_settings.xml" "${HOME}/.m2/settings.xml"
      - run: cat "${HOME}/.m2/settings.xml" 2>/dev/null || true
