name: Specific Maven version example
on: push

jobs:
  job-number-two:
    name: Output some GitHubActions Variables
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: echo "${HOME}"
      - run: echo "${GITHUB_WORKSPACE}"
      - run: python --version
      - run: pwsh --version
      - run: cat ~/.m2/settings.xml 2>/dev/null || true
      - run: cat "${HOME}/.m2/settings.xml" 2>/dev/null || true
      - run: find / -name settings.xml 2>/dev/null || true

